server:
  port: 8083

spring:
  application:
    name: inventory-service
  datasource:
    url: jdbc:postgresql://localhost:5435/inventory
    username: inventory
    password: inventory
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
