/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["createOrder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failed-messages/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["replay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/operator-actions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failed-messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_1"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/failed-messages/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        CreateOrderRequest: {
            /** Format: int64 */
            amountCents?: number;
            sku?: string;
            /** Format: int64 */
            quantity?: number;
        };
        OperatorAction: {
            /** Format: uuid */
            operatorActionId?: string;
            actor?: string;
            actionType?: string;
            targetType?: string;
            targetId?: string;
            /** @enum {string} */
            status?: "DISPATCHED" | "SUCCEEDED" | "FAILED";
            /** Format: date-time */
            dispatchedAt?: string;
            /** Format: date-time */
            completedAt?: string;
            detail?: string;
        };
        FailedMessageRow: {
            /** Format: uuid */
            failedMessageId?: string;
            consumerGroup?: string;
            topic?: string;
            /** Format: int32 */
            partition?: number;
            /** Format: int64 */
            offset?: number;
            messageKey?: string;
            payload?: string;
            headersJson?: string;
            /** Format: uuid */
            eventId?: string;
            eventType?: string;
            failureReason?: string;
            /** @enum {string} */
            status?: "CAPTURED" | "REPLAY_REQUESTED" | "REPLAYED" | "ABANDONED";
            /** Format: date-time */
            capturedAt?: string;
            /** Format: int32 */
            replayAttempts?: number;
            /** Format: date-time */
            lastReplayAt?: string;
            lastReplayError?: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createOrder: {
        parameters: {
            query?: never;
            header?: {
                "Idempotency-Key"?: string;
                traceparent?: string;
                tracestate?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    replay: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": string;
                };
            };
        };
    };
    list: {
        parameters: {
            query?: {
                targetType?: string;
                targetId?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["OperatorAction"][];
                };
            };
        };
    };
    list_1: {
        parameters: {
            query?: {
                openOnly?: boolean;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FailedMessageRow"][];
                };
            };
        };
    };
    get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "*/*": components["schemas"]["FailedMessageRow"];
                };
            };
        };
    };
}
